name: wazo-calld-globalvars
namespace: wazocommunication
version: 1.0.0
author: Wazo authors
display_name: Avoid Asterisk slowdown in the long run
plugin_format_version: 1
min_wazo_version: 24.10
max_wazo_version: 24.13
tags:
  - calls
  - mobile
homepage: https://github.com/wazo-communication/wazo-calld-globalvars-plugin
